# this workflow will run ci
name: ci
on:
  push:
    branches:
      - alpha
      - beta
      - master
  workflow_dispatch:
env:
  zzzz1234: 1
jobs:
  job1:
    strategy:
      matrix:
        architecture:
          # - arm64
          - x64
          # - x86
        os:
          - macos-latest
          - ubuntu-latest
          # - windows-latest
# base - .github/workflows/ci.yml - beg
    env:
      CI_MATRIX_NAME: >
        ${{ matrix.architecture }}
        ${{ matrix.os }}
      CI_WORKFLOW_NAME: >
        ${{ github.workflow }}
        - ${{ github.event_name }}
        - ${{ github.event.inputs.workflow_dispatch_name }}
        - ${{ github.ref_name }}
    name: >
      ${{ matrix.architecture }}
      ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "$(date -u +"%Y-%m-%d %TZ") - ${{ env.CI_WORKFLOW_NAME }}" # "
      # disable autocrlf in windows
      - run: git config --global core.autocrlf false
      # https://github.com/actions/checkout
      - uses: actions/checkout@v3
      # run nodejs coverages and tests
      - run: sh ./ci.sh
# base - .github/workflows/ci.yml - end
